from enum import StrEnum


class WorkflowState(StrEnum):
    RECEIVED = "RECEIVED"
    EXTRACTING = "EXTRACTING"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    VALIDATING = "VALIDATING"
    SEARCHING_AVAILABILITY = "SEARCHING_AVAILABILITY"
    NO_AVAILABILITY = "NO_AVAILABILITY"
    PROPOSED = "PROPOSED"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    APPROVED = "APPROVED"
    REVALIDATING = "REVALIDATING"
    BOOKING = "BOOKING"
    BOOKING_RETRY = "BOOKING_RETRY"
    CONFLICT = "CONFLICT"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    RESCHEDULE_REQUESTED = "RESCHEDULE_REQUESTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
